server:
  port: 8181

spring:
  application:
    name: testEurekaServer


eureka:
  client:
    register-with-eureka: false #Server? ???? client? ??? ??? ??
    fetch-registry: false # default? true?? server??? registry ??? ???? ??? ???? 30??? ??????? ?? ??
    service-url:
      defaultZone : http://localhost:8181/eureka/